load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ws_origin_policy",
    srcs = ["WsOriginPolicy.cpp"],
    hdrs = ["WsOriginPolicy.h"],
    copts = ["-std=gnu++23"],
    visibility = ["//net:__subpackages__"],
)
