load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "livekit_node_registry",
    srcs = ["LivekitNodeRegistry.cpp"],
    hdrs = ["LivekitNodeRegistry.h"],
    deps = [
        "//domains/ids:domain_ids",
    ],
    visibility = ["//visibility:public"],
)