load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ping_command",
    hdrs = [
        "PingCommand.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//app:i_command",
    ],
)
