"Command list for app/BUILD"

COMMAND_LIST = [
    "//app/commands/session:bootstrap_command",
    "//app/commands/session:authenticate_command",
    "//app/commands/system:disconnection_command",
    "//app/commands/activity:select_active_channel_command",
    "//app/commands/activity:typing_command",
    "//app/commands/message:send_message_command",
    "//app/commands/message:fetch_latest_messages_command",
    "//app/commands/message:fetch_messages_before_command",
    "//app/commands/hub:create_hub_command",
    "//app/commands/hub:join_hub_command",
    "//app/commands/hub:create_hub_join_code_command",
    "//app/commands/hub:leave_hub_command",
    "//app/commands/hub:remove_hub_command",
    "//app/commands/hub:rename_hub_command",
    "//app/commands/hub:update_hub_command",
    "//app/commands/user:update_user_command",
    "//app/commands/channel:create_channel_command",
    "//app/commands/channel:rename_channel_command",
    # "//app/commands/system:connection_command",
    # "//app/commands:join_channel_command",
    # "//app/commands:send_message_command",
    # "//app/commands:create_channel_command",
    # "//app/commands:delete_channel_command",
    # "//app/commands:rename_channel_command",
    # "//app/commands:delete_hub_command",
    # "//app/commands:create_hub_command",
    # "//app/commands:rename_hub_command",
    # "//app/commands:get_hub_invite_command",
    # "//app/commands:join_hub_by_invite_command",
    # "//app/commands:leave_hub_command",
    # "//app/commands:update_member_role_command",
    # "//app/commands:update_profile_command",
]
