load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "ts_queue",
    hdrs = [
        "ThreadSafeQueue.h",
    ],
    copts = ["-std=gnu++23"],
    visibility = ["//visibility:public"],
)
