load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "on_memory_cache",
    srcs = [
        "OnMemoryCache.cpp",
    ],
    hdrs = [
        "AnyKey.h",
        "ICache.h",
        "OnMemoryCache.h",
    ],
    copts = ["-std=gnu++23"],
    visibility = ["//visibility:public"],
)
