load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "common",
    srcs = [
        "ChatServer.cpp",
    ],
    hdrs = [
        "ChatServer.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//domains",
    ],
)
