cc_library(
    name = "common",
    srcs = [
        "ChatServer.cpp",
    ],
    hdrs = [
        "Channel.h",
        "ChatServer.h",
        "Message.h",
        "User.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
)
