# file group for core/database/sql/database_schema.sql
filegroup(
    name = "database_schema_sql",
    srcs = glob(["*.sql"]),
    visibility = ["//visibility:public"],
)

exports_files(["V001__init.sql"])
