-- V001__init.sql
-- Baseline schema for hubs → channels → membership → messages.
-- Run this inside the target database (e.g., chat_db).

BEGIN;

-- ---------- helper: updated_at auto-maintenance ----------
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END$$;

-- ---------- users ----------
CREATE TABLE IF NOT EXISTS users (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username        TEXT NOT NULL UNIQUE,
  password_hash   TEXT NOT NULL,
  email           TEXT,
  public_key      TEXT,                 -- reserved for future E2EE
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TRIGGER trg_users_updated_at
  BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------- hubs ----------
CREATE TABLE IF NOT EXISTS hubs (
  id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name            TEXT NOT NULL,
  owner_id        BIGINT REFERENCES users(id) ON DELETE SET NULL,  -- allow owner transfer
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT unique_owner_hub UNIQUE (owner_id, name)
);

CREATE TRIGGER trg_hubs_updated_at
  BEFORE UPDATE ON hubs
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- When a hub is created with a non-null owner, ensure owner is also a member with 'owner' role.
CREATE OR REPLACE FUNCTION ensure_owner_membership()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.owner_id IS NOT NULL THEN
    INSERT INTO hub_members(hub_id, user_id, role)
    VALUES (NEW.id, NEW.owner_id, 'owner')
    ON CONFLICT (hub_id, user_id) DO NOTHING;
  END IF;
  RETURN NEW;
END$$;

CREATE TRIGGER trg_hubs_owner_membership
  AFTER INSERT ON hubs
  FOR EACH ROW EXECUTE FUNCTION ensure_owner_membership();

-- ---------- hub_members ----------
CREATE TABLE IF NOT EXISTS hub_members (
  hub_id   BIGINT NOT NULL REFERENCES hubs(id)   ON DELETE CASCADE,
  user_id  BIGINT NOT NULL REFERENCES users(id)  ON DELETE CASCADE,
  role     TEXT   NOT NULL CHECK (role IN ('owner','admin','member')),
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (hub_id, user_id)
);

-- Helpful for “my hubs” queries
CREATE INDEX IF NOT EXISTS idx_hub_members_user_id ON hub_members(user_id);

-- ---------- channels ----------
CREATE TABLE IF NOT EXISTS channels (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hub_id     BIGINT NOT NULL REFERENCES hubs(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  type       TEXT NOT NULL CHECK (type IN ('text','voice')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT unique_channel_per_hub UNIQUE (hub_id, name)
);

CREATE INDEX IF NOT EXISTS idx_channels_hub_id ON channels(hub_id);

CREATE TRIGGER trg_channels_updated_at
  BEFORE UPDATE ON channels
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------- messages (text only for now) ----------
CREATE TABLE IF NOT EXISTS messages (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  channel_id  BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  sender_id   BIGINT NOT NULL REFERENCES users(id)    ON DELETE CASCADE,
  content     TEXT NOT NULL,        -- can be encrypted later
  sent_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- History paging by channel, newest first
CREATE INDEX IF NOT EXISTS idx_messages_channel_sent_at
  ON messages(channel_id, sent_at DESC);

COMMIT;
-- ---------- End of schema ----------
