# load("@rules_cc//cc:cc_library.bzl", "cc_library")

# cc_library(
#     name = "disconnect_command",
#     srcs = ["DisconnectCommand.cpp"],
#     hdrs = ["DisconnectCommand.h"],
#     copts = ["-std=gnu++23"],
#     visibility = ["//visibility:public"],
#     deps = [
#         "//app/commands:i_command",
#         "//app/memory:on_memory_cache",
#         "//app/services:hub_publisher",
#         "//net:client_gateway",
#         "@nlohmann_json",
#     ],
# )
