load("@rules_cc//cc:cc_test.bzl", "cc_test")


# cc_test(
#     name = "thread_safe_queue",
#     srcs = ["thread_safe_queue.cc"],
#     deps = [
#         "//app/queue:event_queue",
#         "//app/queue:outgoing_queue",
#         "@googletest//:gtest_main",
#     ],
# )

